src/pages/home/index.module.scss
=> fix:修改样式，选择模版的弹窗响应式问题 #6

src/components/collapse/index.module.scss, src/components/collapse/index.tsx
=> perf: ⚡️优化edit页面文件列表FILES左侧箭头转向的交互

src/components/file-modal/index.tsx
=> perf: ⚡️优化, 在编辑，新建文件或者文件夹时自动对准焦点

src/components/file-modal/index.tsx
=> perf: ⚡️ file Modal框增加回车添加修改文件或文件夹

src/assets/styles/var.scss, src/pages/edit/component/file/index.module.scss, src/pages/edit/component/setting/index.module.scss, src/pages/edit/component/setting/index.tsx
=> style: 🎨  setting部分增加更改一些样式，优化一些代码

src/components/collapse/index.tsx, src/store/modules/code.ts
=> fix: 🧩 修富文件操作问题，目前没有触发父元素事件，因为可能会造成文件夹折叠展开影响交互。

src/components/file-modal/index.tsx, src/types/index.ts
=> fix 🧩: 修复删除文件夹删除文件名称的问题

.github/workflows/lint.yml, eslint.config.cjs, package.json, pnpm-lock.yaml, src/__tests__/Hello.test.tsx, src/components/Hello.tsx, tsconfig.json, vitest.config.ts, vitest.setup.ts
- Closes #
- Related to #
feat: 🚀 added unit testing capabilities
=> feat: 🚀 added unit testing capabilities

next.config.mjs, package.json, pnpm-lock.yaml, src/app/layout.tsx
- Closes #
- Related to #
feat: 🚀 add next-devtool
=> feat: 🚀 add next-devtool

package.json, pnpm-lock.yaml, src/app/globals.css
- Closes #
- Related to #
framer-motion bug
报错通过回退framer-motion版本解决，警告通过添加position解决
=> fix：fix framer-motion bug

next.config.mjs, pnpm-lock.yaml, src/app/page.tsx, tailwind.config.ts
- Closes #
- Related to #
fix: 🧩 修复打包构建失败的问题
=> fix: 🧩 修复打包构建失败的问题

package.json, pnpm-lock.yaml, src/app/(main)/(router)/dashboard/page.tsx, src/app/(main)/(router)/templates/page.tsx, src/app/(main)/layout.tsx, src/app/globals.css, src/app/page.tsx, src/components/common/Avatar/index.tsx, src/components/main/header/index.tsx, src/components/main/sider/index.tsx, src/components/ui/avatar/index.tsx, src/components/ui/button/index.tsx, tailwind.config.ts
- Closes #
- Related to #
引入shadcn，初始化dashboard页面
=> feat: init dashboard

package.json, pnpm-lock.yaml, src/app/edit/page.tsx, src/components/resize-handle/index.tsx
- Closes #
- Related to #
feat: 🚀 initializes the editor page
=> feat: 🚀 initializes the editor page

package.json, pnpm-lock.yaml, src/app/edit/(main)/(router)/file/page.tsx, src/app/edit/(main)/(router)/search/page.tsx, src/app/edit/layout.tsx, src/components/preview/index.tsx, src/utils/constants.ts, src/utils/index.ts
- Closes #
- Related to #
feat: 🚀 the edit page is rearranged and the preview component added
=> feat: 🚀 the edit page is rearranged and the preview component added

pnpm-lock.yaml, src/app/edit/layout.tsx, src/app/page.tsx, src/components/edit/header/index.tsx, src/components/main/header/index.tsx, src/components/main/sider/index.tsx, src/utils/constants.ts
- Closes #
- Related to #
初始化edit header ，部分路由改用constant
=> feat: init edit header

package.json, pnpm-lock.yaml, src/app/edit/layout.tsx, src/components/editor/index.tsx
- Closes #
- Related to #
feat: 🚀 initializes the monaco editor editing function
=> feat: 🚀 initializes the monaco editor editing function

package.json, src/app/community/page.tsx
- Closes #
- Related to #
feat: 🚀 add community comments
=> feat: 🚀 add community comments

package.json, pnpm-lock.yaml, src/app/community/page.tsx
- Closes #
- Related to #
fix: 🧩 use @giscus/react to configure and render the commenting system
=> fix: 🧩 use @giscus/react to configure and render the commenting system

CONTRIBUTING-zh.md, CONTRIBUTING.md
…ntribution guide
- Closes #
- Related to #
Correction of upstream warehouse addresses in the contribution guide
=> fix(contribution): fix the wrong address for upstream warehouse

pnpm-lock.yaml, src/app/edit/layout.tsx, src/components/editor/index.tsx, src/components/editor/utils.ts
- Closes #
- Related to #
fix: 🧩  fix vercel package build failed
=> fix: 🧩  fix vercel package build failed

src/app/edit/(main)/(router)/ai/page.tsx, src/app/edit/layout.tsx, src/utils/constants.ts
- Closes #
- Related to #
feat: 🚀 initialize the ai page
=> feat: 🚀 initialize the ai page

.github/workflows/lint.yml, src/app/edit/(main)/(router)/file/page.tsx, src/components/edit/tabbar/index.tsx, src/components/editor/index.tsx, src/components/editor/utils.ts
allow click to show flie and add scrolltoview for tabs
- Closes #
- Related to #
=> featre：allow click to show flie and add scrolltoview for tabs

package.json, pnpm-lock.yaml, src/components/avatarPopover/index.tsx, src/components/avatarPopover/menu/index.tsx, src/components/main/header/index.tsx, tailwind.config.ts
- Closes #
- Related to #
feat: add avatarPopover component
=> feat:add avatarPopover component

src/components/edit/header/index.tsx
- Closes #
- Related to #
feat:add avatarpopover to edit/file route
=> feat:add avatarpopover to edit/file route

src/components/edit/tabItem/index.tsx, src/components/edit/tabbar/index.tsx
- Closes #
- Related to #
修复了tab drag到editor控制台报错的问题，重新引入file的默认icon
=> fix: drag bug and img loss

package.json, pnpm-lock.yaml, src/app/edit/(main)/(router)/file/page.tsx, src/components/edit/tabItem/index.tsx, src/components/edit/tabbar/index.tsx, src/components/editor/index.tsx, src/components/extension/tree-view-api/index.tsx, src/components/file/fileItem/index.tsx, src/components/file/fileTree/index.tsx
- Closes #
- Related to #
初始化fileTree
=> feat: init fileTree

src/app/edit/layout.tsx
- Closes #
- Related to #
feat: 🚀 新增编辑页面 tab 栏切换动画
=> feat: 🚀 新增编辑页面 tab 栏切换动画

next.config.mjs, package.json
- Closes #
- Related to #
fix: 🧩 修复了 lock 文件缺少格式化而导致的大量 diff 变更
=> fix: 🧩 修复了 lock 文件缺少格式化而导致的大量 diff 变更

src/components/ui/avatar/index.stories.tsx, src/components/ui/badge/index.stories.tsx, src/components/ui/button/index.stories.tsx, src/components/ui/dialog/index.stories.tsx, src/components/ui/dropdown-menu/index.stories.tsx, src/components/ui/input/index.stories.tsx, src/components/ui/scroll-area/index.stories.tsx
- Closes #
- Related to #
docs: 📚 添加 ui 组件文档
=> docs: 📚 添加 ui 组件文档

src/app/edit/layout.tsx, src/components/edit/tabItem/index.tsx, src/components/editor/index.tsx, src/components/file/fileItem/index.tsx, src/store/editorStore.tsx, src/utils/editor.ts
- Closes #
- Related to #
https://github.com/xun082/online-edit-web/commit/4a9782397672e86de2d68e3bbe16b9227cc4bdba
在该次修改时破坏了多开功能,这里修复一下
=> fix:修复多开功能

src/app/edit/(main)/(router)/settings/page.tsx, src/components/ui/select/index.stories.tsx, src/components/ui/select/index.tsx, src/components/ui/tooltip/index.stories.tsx, src/components/ui/tooltip/index.tsx
- Closes #
- Related to #
chore: 🔨 improve code structure and add documentation
=> chore: 🔨 improve code structure and add documentation

next.config.mjs, vercel.json
- Closes #
- Related to #
解决配置 Cross-Origin-Embedder-Policy 导致的图片和资源加载错误
=> fix: 解决配置 Cross-Origin-Embedder-Policy 导致的图片和资源加载错误

vercel.json
- Closes #
- Related to #
fix: 修复vercel.json
=> fix: 修复vercel.json

src/app/edit/(main)/(router)/file/page.tsx, src/components/editor/index.tsx, src/components/file/fileTree/index.tsx, src/components/file/pendingFileItem/index.tsx
- Closes #
- Related to #
文件编辑后同步到webContainer文件系统
=> feat: 文件编辑后同步到webcontainer文件系统

src/app/page.tsx
- Closes #
- Related to #
style: 🎨 优化首页代码
=> style: 🎨 优化首页代码

next.config.mjs, vercel.json
=> fix: 修复引入外部资源失效

package.json, pnpm-lock.yaml, src/app/(main)/(router)/dashboard/page.tsx, src/app/(main)/(router)/templates/page.tsx, src/app/edit/[projectId]/(main)/(router)/file/page.tsx, src/app/edit/[projectId]/layout.tsx, src/components/edit/header/index.tsx, src/components/modals/create-project-modal/index.tsx, src/components/preview/booting/index.tsx, src/components/preview/index.tsx, src/components/webContainerProvider/index.tsx, src/store/webContainerStore.tsx, src/utils/zip.ts
- Closes #
- Related to #
实现下载,修改部分样式
=> feat:实现下载,修改部分样式

src/app/page.tsx, src/components/home/header/index.tsx, tailwind.config.ts
=> style: 🎨 首页样式美化

src/app/(main)/(router)/dashboard/page.tsx
=> fix:修复选择更多模版按钮文字在小尺寸屏幕下换行

src/components/editor/index.tsx
第一次打开文件为空白，报错如图所示
- Closes #
- Related to #
在edit onMount 时创建defaultModel可以解决这个问题
=> fix:修复第一次打开文件时显示空白内容的bug

src/app/(main)/(router)/dashboard/page.tsx, src/components/modals/create-project-modal/index.tsx
- Closes #
- Related to #
可以通过首页的快速开始card创建项目
=> feat:allow quick start project

package.json, pnpm-lock.yaml, src/app/layout.tsx, src/components/nextTopLoader/index.tsx
- Closes #
- Related to #
添加了页面跳转时浏览器top的进度条效果
=> feat: add progressBar

src/app/edit/[projectId]/layout.tsx, src/components/extension/tree-view-api/index.tsx, src/components/file/fileItem/index.tsx, src/components/file/fileTree/index.tsx, src/components/file/pendingFileItem/index.tsx
- Closes #
- Related to #
可以对文件和·文件夹重命名
=> feat: allow rename file

src/app/edit/[projectId]/layout.tsx, src/utils/constants.ts
- Closes #
- Related to #
修复了编辑页侧边栏切换问题
=> fix: 修复动态路由导致的跳转问题

src/components/file/fileTree/index.tsx, src/components/preview/index.tsx
- Closes #
- Related to #
文件目录没有排序, 排一下体验稍微好点
[顺带修复] 预览区域的输入框链接没有同步到 iframe
=> feat: 新增目录排序功能

package.json, pnpm-lock.yaml, src/app/edit/[projectId]/(main)/(router)/search/page.tsx, src/components/fileSearch/ToolBtn/index.tsx, src/components/fileSearch/includeAndExclude/index.tsx, src/components/fileSearch/input/index.tsx, src/components/fileSearch/matchResult/index.tsx, src/components/fileSearch/matchResultTree/index.tsx, src/components/fileSearch/replace/index.tsx, src/components/fileSearch/search/index.tsx, src/components/ui/accordion/index.stories.tsx, src/components/ui/accordion/index.tsx, src/store/fileSearchStore.tsx, src/utils/debounce.ts, src/utils/index.ts, src/utils/match.ts, src/utils/matchHelper.ts
=> feat: 🚀 新增全局文件搜索功能和局部替换功能及其附属功能

package.json, src/components/file/fileTree/index.tsx
1.The current folder is not sorted
2.lock pnpm version is not required
- Closes #
- Related to #
1.fix file sort
2.fix pnpm version
=> fix file sort

src/app/edit/[projectId]/(main)/(router)/file/page.tsx, src/app/edit/[projectId]/(main)/(router)/settings/page.tsx, src/components/edit/tabbar/index.tsx, src/components/editor/index.tsx, src/store/editorStore.tsx, src/store/uploadFileDataStore.tsx, src/store/webContainerStore.tsx, src/utils/constants.ts
- Closes #114 
- Related to #
基于shiki实现monaco的主题切换
close https://github.com/xun082/online-edit-web/issues/114
=> feat: allow change monaco theme

src/app/edit/[projectId]/(main)/(router)/search/page.tsx, src/utils/match.ts, src/utils/matchHelper.ts
=> fix: 🧩 修复文件搜索读取.gitingnore文件导致搜索结果异常的一些问题

src/app/edit/[projectId]/(main)/(router)/search/page.tsx, src/components/fileSearch/matchResult/index.tsx, src/components/fileSearch/matchResultTree/index.tsx, src/utils/match.ts, src/utils/matchHelper.ts
=> perf: ⚡️ 优化文件搜索结果树模式显示渲染；优化搜索逻辑、减少代码冗余。

package.json, pnpm-lock.yaml, src/app/cooperation/(router)/[room]/layout.tsx, src/app/cooperation/(router)/[room]/page.tsx, src/app/cooperation/layout.tsx, src/components/cooperation/collaboratorAvatarList/index.tsx, src/components/cooperation/cooperationEditor/cooperationEditorHeader/index.tsx, src/components/cooperation/cooperationEditor/index.tsx, src/components/cooperation/header/index.tsx, src/components/cooperation/taskDescription/index.tsx, src/components/cooperation/taskList/index.tsx, src/components/extension/tree-view-api/index.tsx, src/store/taskStore.tsx, src/utils/constants.ts, tailwind.config.ts
- Closes #
- Related to #
实现最基础的协同功能以及题目搜索,切换
=> feat: 实现最基础的协同功能

.env.development, .env.production, src/app/(main)/(router)/login/page.tsx, src/app/(main)/layout.tsx, src/app/globals.css, src/app/layout.tsx, src/app/page.tsx, src/components/avatarPopover/index.tsx, src/store/authStore.tsx, src/utils/apis.ts, src/utils/constants.ts, tailwind.config.ts
- Closes #40 
- Related to #
❌ ~~新增github第三方登录~~
✅ 邮箱验证码登录
=> feat: 🚀 添加邮箱验证码登录

package.json, pnpm-lock.yaml, src/app/globals.css, src/components/cooperation/cooperationEditor/index.tsx, src/components/cooperation/cursor/index.tsx, src/components/cooperation/header/index.tsx, src/components/editor/index.tsx, src/hooks/usePerfectCursor.ts, src/store/cooperationPersonStore.tsx, src/utils/createColorFromId.ts, src/utils/hexToRgba.ts, src/utils/index.ts, src/utils/throttle.ts
- Closes #
- Related to #
实现基本的协同光标,选区,头像
=> feat: 完善协同选区,光标,头像效果

next.config.mjs
- Closes #
- Related to #
修复了nextconfig导致的协同页面图片跨域无法显示的问题
=> fix: nextconfig

ecosystem.config.cjs, package.json, tsconfig.json
- Closes #
- Related to #
feat: 🚀 新增 pm2 配置用于部署
=> feat: 🚀 新增 pm2 配置用于部署

src/app/cooperation/(router)/[room]/page.tsx, src/components/cooperation/cooperationEditor/index.tsx
- Closes #
- Related to #
禁止协同文档组件ssr,解决window undefined报错,修正请求url,调整cursor位置变换节流时间
=> feat: 修复协同部分bug

src/components/cooperation/cooperationEditor/index.tsx
- Closes #
- Related to #
修复光标无法正确清除
=> fix: 修复光标清除

README.md
- Closes #
- Related to #
docs: 📚 修改文档
=> docs: 📚 修改文档
